// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvh7MrK3PLBfkkKKFtgmWPQdPIDSptofA',
    appId: '1:86570266580:web:a1153052b1843ad5017041',
    messagingSenderId: '86570266580',
    projectId: 'sitemark-166de',
    authDomain: 'sitemark-166de.firebaseapp.com',
    storageBucket: 'sitemark-166de.appspot.com',
    measurementId: 'G-3HCDBS69QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_rUhNZxQ25YoWQcYmR4o1L5NPzms05tk',
    appId: '1:86570266580:android:37637b361a248ad4017041',
    messagingSenderId: '86570266580',
    projectId: 'sitemark-166de',
    storageBucket: 'sitemark-166de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD7UiKKKD_gFCGNss2ELFcogmzI1OXFCk',
    appId: '1:86570266580:ios:1a00f6522b92e5fc017041',
    messagingSenderId: '86570266580',
    projectId: 'sitemark-166de',
    storageBucket: 'sitemark-166de.appspot.com',
    androidClientId: '86570266580-0ra74m2mrtqop4t3k08f3kivq8408org.apps.googleusercontent.com',
    iosClientId: '86570266580-k9n40rismmb1qc3gnd1kc9jo1etjn3gg.apps.googleusercontent.com',
    iosBundleId: 'com.example.sitemark',
  );
}
